
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DonationProvider } from "./user/context/DonationContext";
import { RequestProvider } from "./user/context/RequestContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BloodOrg",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DonationProvider>
          <RequestProvider>
            {children}
          </RequestProvider>
        </DonationProvider>
      </body>
    </html>
  );
}
